services:
  tessera1:
    image: quorumengineering/tessera:24.4.2
    container_name: tessera1
    volumes:
      - ./tessera1/tessera-config.json:/config/tessera-config.json
      - ./tessera1/data:/data
    command: -configfile /config/tessera-config.json
    networks:
      besu-network:
        ipv4_address: 172.20.0.10

  tessera2:
    image: quorumengineering/tessera:24.4.2
    container_name: tessera2
    volumes:
      - ./tessera2/tessera-config.json:/config/tessera-config.json
      - ./tessera2/data:/data
    command: -configfile /config/tessera-config.json
    networks:
      besu-network:
        ipv4_address: 172.20.0.11

  tessera3:
    image: quorumengineering/tessera:24.4.2
    container_name: tessera3
    volumes:
      - ./tessera3/tessera-config.json:/config/tessera-config.json
      - ./tessera3/data:/data
    command: -configfile /config/tessera-config.json
    networks:
      besu-network:
        ipv4_address: 172.20.0.12

  tessera4:
    image: quorumengineering/tessera:24.4.2
    container_name: tessera4
    volumes:
      - ./tessera4/tessera-config.json:/config/tessera-config.json
      - ./tessera4/data:/data
    command: -configfile /config/tessera-config.json
    networks:
      besu-network:
        ipv4_address: 172.20.0.13
  node1:
    image: hyperledger/besu:24.1.0
    container_name: besu-node1
    user: root
    depends_on:
      - tessera1
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - ./node1/keys:/opt/besu/keys
      - ./genesis.json:/opt/besu/genesis.json
      - node1-data:/opt/besu/data
    command: >
      --genesis-file=/opt/besu/genesis.json
      --node-private-key-file=/opt/besu/keys/key
      --data-path=/opt/besu/data
      --p2p-host=0.0.0.0
      --p2p-port=30303
      --rpc-http-enabled
      --rpc-http-api=ETH,NET,QBFT,ADMIN,WEB3,EEA,PRIV
      --rpc-http-host=0.0.0.0
      --rpc-http-port=8545
      --rpc-http-cors-origins=all
      --host-allowlist=*
      --min-gas-price=0
      --tx-pool-min-gas-price=0
      --privacy-enabled
      --privacy-url=http://tessera1:9082
      --privacy-public-key-file=/opt/besu/keys/tessera1.pub
    networks:
      besu-network:
        ipv4_address: 172.20.0.2

  node2:
    image: hyperledger/besu:24.1.0
    container_name: besu-node2
    user: root
    depends_on:
      - node1
      - tessera2
    ports:
      - "8546:8545"
    volumes:
      - ./node2/keys:/opt/besu/keys
      - ./genesis.json:/opt/besu/genesis.json
      - node2-data:/opt/besu/data
    command: >
      --genesis-file=/opt/besu/genesis.json
      --node-private-key-file=/opt/besu/keys/key
      --data-path=/opt/besu/data
      --p2p-host=0.0.0.0
      --p2p-port=30303
      --bootnodes=enode://312886c5e20406d8fcd4765830ec32c618cdd13a5cb747cfd5688e616d882cd910eef5177e069bbd0707b0383d02d06326314451edad9bbb57dfb888c3083ffa@172.20.0.2:30303
      --rpc-http-enabled
      --rpc-http-api=ETH,NET,QBFT,ADMIN,WEB3,EEA,PRIV
      --rpc-http-host=0.0.0.0
      --rpc-http-port=8545
      --rpc-http-cors-origins=all
      --host-allowlist=*
      --min-gas-price=0
      --tx-pool-min-gas-price=0
      --privacy-enabled
      --privacy-url=http://tessera2:9082
      --privacy-public-key-file=/opt/besu/keys/tessera2.pub
    networks:
      besu-network:
        ipv4_address: 172.20.0.3

  node3:
    image: hyperledger/besu:24.1.0
    container_name: besu-node3
    user: root
    depends_on:
      - node1
      - tessera3
    ports:
      - "8547:8545"
    volumes:
      - ./node3/keys:/opt/besu/keys
      - ./genesis.json:/opt/besu/genesis.json
      - node3-data:/opt/besu/data
    command: >
      --genesis-file=/opt/besu/genesis.json
      --node-private-key-file=/opt/besu/keys/key
      --data-path=/opt/besu/data
      --p2p-host=0.0.0.0
      --p2p-port=30303
      --bootnodes=enode://312886c5e20406d8fcd4765830ec32c618cdd13a5cb747cfd5688e616d882cd910eef5177e069bbd0707b0383d02d06326314451edad9bbb57dfb888c3083ffa@172.20.0.2:30303
      --rpc-http-enabled
      --rpc-http-api=ETH,NET,QBFT,ADMIN,WEB3,EEA,PRIV
      --rpc-http-host=0.0.0.0
      --rpc-http-port=8545
      --rpc-http-cors-origins=all
      --host-allowlist=*
      --min-gas-price=0
      --tx-pool-min-gas-price=0
      --privacy-enabled
      --privacy-url=http://tessera3:9082
      --privacy-public-key-file=/opt/besu/keys/tessera3.pub
    networks:
      besu-network:
        ipv4_address: 172.20.0.4

  node4:
    image: hyperledger/besu:24.1.0
    container_name: besu-node4
    user: root
    depends_on:
      - node1
      - tessera4
    ports:
      - "8548:8545"
    volumes:
      - ./node4/keys:/opt/besu/keys
      - ./genesis.json:/opt/besu/genesis.json
      - node4-data:/opt/besu/data
    command: >
      --genesis-file=/opt/besu/genesis.json
      --node-private-key-file=/opt/besu/keys/key
      --data-path=/opt/besu/data
      --p2p-host=0.0.0.0
      --p2p-port=30303
      --bootnodes=enode://312886c5e20406d8fcd4765830ec32c618cdd13a5cb747cfd5688e616d882cd910eef5177e069bbd0707b0383d02d06326314451edad9bbb57dfb888c3083ffa@172.20.0.2:30303
      --rpc-http-enabled
      --rpc-http-api=ETH,NET,QBFT,ADMIN,WEB3,EEA,PRIV
      --rpc-http-host=0.0.0.0
      --rpc-http-port=8545
      --rpc-http-cors-origins=all
      --host-allowlist=*
      --min-gas-price=0
      --tx-pool-min-gas-price=0
      --privacy-enabled
      --privacy-url=http://tessera4:9082
      --privacy-public-key-file=/opt/besu/keys/tessera4.pub
    networks:
      besu-network:
        ipv4_address: 172.20.0.5

  node5:
    image: hyperledger/besu:24.1.0
    container_name: besu-node5-archive
    user: root
    depends_on:
      - node1
    ports:
      - "8549:8545"
    volumes:
      - ./node5/keys:/opt/besu/keys
      - ./genesis.json:/opt/besu/genesis.json
      - node5-data:/opt/besu/data
    command: >
      --genesis-file=/opt/besu/genesis.json
      --node-private-key-file=/opt/besu/keys/key
      --data-path=/opt/besu/data
      --p2p-host=0.0.0.0
      --p2p-port=30303
      --bootnodes=enode://312886c5e20406d8fcd4765830ec32c618cdd13a5cb747cfd5688e616d882cd910eef5177e069bbd0707b0383d02d06326314451edad9bbb57dfb888c3083ffa@172.20.0.2:30303
      --rpc-http-enabled
      --rpc-http-api=ETH,NET,ADMIN,WEB3,DEBUG,TRACE
      --data-storage-format=FOREST
      --sync-mode=FULL
      --rpc-http-host=0.0.0.0
      --rpc-http-port=8545
      --rpc-http-cors-origins=all
      --host-allowlist=*
      --min-gas-price=0
      --tx-pool-min-gas-price=0
    networks:
      besu-network:
        ipv4_address: 172.20.0.6
    mem_limit: 4g

  # node6:
  #   image: hyperledger/besu:24.1.0
  #   container_name: besu-node6
  #   user: root
  #   depends_on:
  #     - node1
  #   ports:
  #     - "8550:8545"
  #   volumes:
  #     - ./node6/keys:/opt/besu/keys
  #     - ./genesis.json:/opt/besu/genesis.json
  #     - node6-data:/opt/besu/data
  #   command: >
  #     --genesis-file=/opt/besu/genesis.json
  #     --node-private-key-file=/opt/besu/keys/key
  #     --data-path=/opt/besu/data
  #     --p2p-host=0.0.0.0
  #     --p2p-port=30303
  #     --bootnodes=enode://312886c5e20406d8fcd4765830ec32c618cdd13a5cb747cfd5688e616d882cd910eef5177e069bbd0707b0383d02d06326314451edad9bbb57dfb888c3083ffa@172.20.0.2:30303
  #     --rpc-http-enabled
  #     --rpc-http-api=ETH,NET,QBFT,ADMIN,WEB3
  #     --rpc-http-host=0.0.0.0
  #     --rpc-http-port=8545
  #     --rpc-http-cors-origins=all
  #     --host-allowlist=*
  #     --min-gas-price=0
  #     --tx-pool-min-gas-price=0
  #   networks:
  #     - besu-network

  # node7:
  #   image: hyperledger/besu:24.1.0
  #   container_name: besu-node7
  #   user: root
  #   depends_on:
  #     - node1
  #   ports:
  #     - "8551:8545"
  #   volumes:
  #     - ./node7/keys:/opt/besu/keys
  #     - ./genesis.json:/opt/besu/genesis.json
  #     - node7-data:/opt/besu/data
  #   command: >
  #     --genesis-file=/opt/besu/genesis.json
  #     --node-private-key-file=/opt/besu/keys/key
  #     --data-path=/opt/besu/data
  #     --p2p-host=0.0.0.0
  #     --p2p-port=30303
  #     --bootnodes=enode://312886c5e20406d8fcd4765830ec32c618cdd13a5cb747cfd5688e616d882cd910eef5177e069bbd0707b0383d02d06326314451edad9bbb57dfb888c3083ffa@172.20.0.2:30303
  #     --rpc-http-enabled
  #     --rpc-http-api=ETH,NET,QBFT,ADMIN,WEB3
  #     --rpc-http-host=0.0.0.0
  #     --rpc-http-port=8545
  #     --rpc-http-cors-origins=all
  #     --host-allowlist=*
  #     --min-gas-price=0
  #     --tx-pool-min-gas-price=0
  #   networks:
  #     - besu-network

  # node8:
  #   image: hyperledger/besu:24.1.0
  #   container_name: besu-node8
  #   user: root
  #   depends_on:
  #     - node1
  #   ports:
  #     - "8552:8545"
  #   volumes:
  #     - ./node8/keys:/opt/besu/keys
  #     - ./genesis.json:/opt/besu/genesis.json
  #     - node8-data:/opt/besu/data
  #   command: >
  #     --genesis-file=/opt/besu/genesis.json
  #     --node-private-key-file=/opt/besu/keys/key
  #     --data-path=/opt/besu/data
  #     --p2p-host=0.0.0.0
  #     --p2p-port=30303
  #     --bootnodes=enode://312886c5e20406d8fcd4765830ec32c618cdd13a5cb747cfd5688e616d882cd910eef5177e069bbd0707b0383d02d06326314451edad9bbb57dfb888c3083ffa@172.20.0.2:30303
  #     --rpc-http-enabled
  #     --rpc-http-api=ETH,NET,QBFT,ADMIN,WEB3
  #     --rpc-http-host=0.0.0.0
  #     --rpc-http-port=8545
  #     --rpc-http-cors-origins=all
  #     --host-allowlist=*
  #     --min-gas-price=0
  #     --tx-pool-min-gas-price=0
  #   networks:
  #     - besu-network

  # node9:
  #   image: hyperledger/besu:24.1.0
  #   container_name: besu-node9
  #   user: root
  #   depends_on:
  #     - node1
  #   ports:
  #     - "8553:8545"
  #   volumes:
  #     - ./node9/keys:/opt/besu/keys
  #     - ./genesis.json:/opt/besu/genesis.json
  #     - node9-data:/opt/besu/data
  #   command: >
  #     --genesis-file=/opt/besu/genesis.json
  #     --node-private-key-file=/opt/besu/keys/key
  #     --data-path=/opt/besu/data
  #     --p2p-host=0.0.0.0
  #     --p2p-port=30303
  #     --bootnodes=enode://312886c5e20406d8fcd4765830ec32c618cdd13a5cb747cfd5688e616d882cd910eef5177e069bbd0707b0383d02d06326314451edad9bbb57dfb888c3083ffa@172.20.0.2:30303
  #     --rpc-http-enabled
  #     --rpc-http-api=ETH,NET,QBFT,ADMIN,WEB3
  #     --rpc-http-host=0.0.0.0
  #     --rpc-http-port=8545
  #     --rpc-http-cors-origins=all
  #     --host-allowlist=*
  #     --min-gas-price=0
  #     --tx-pool-min-gas-price=0
  #   networks:
  #     - besu-network
  redis:
    image: redis:8-alpine
    container_name: besu-redis
    restart: unless-stopped
    ports:
      - "6379:6379"                 # expose to host for inspection
    volumes:
      - redis-data:/data            # persist data across restarts
    command: redis-server --appendonly yes  # enable AOF persistence
    networks:
      besu-network:
        ipv4_address: 172.20.0.7

  # ── BLOCK COLLECTOR ───────────────────────────────────────
  block-collector:
    build:
      context: ./collector
      dockerfile: Dockerfile
    container_name: besu-block-collector
    restart: unless-stopped
    depends_on:
      - node1
      - redis
    environment:
      - BESU_RPC_URL=http://172.20.0.2:8545
      - REDIS_URL=redis://redis:6379
      - POLL_INTERVAL_MS=2000        # match your blockperiodseconds
    networks:
      besu-network:
        ipv4_address: 172.20.0.8

volumes:
  node1-data:
  node2-data:
  node3-data:
  node4-data:
  node5-data:
  redis-data:
  # tessera1-data:
  # tessera2-data:
  # tessera3-data:
  # tessera4-data:
  # node6-data:
  # node7-data:
  # node8-data:
  # node9-data:

networks:
  besu-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16